---
- name: Install required font package
  community.general.homebrew_cask:
    name: font-meslo-lg-nerd-font
    state: present
    path: "/opt/workbrew/bin:/opt/homebrew/bin:/usr/local/bin"

- name: Create Alacritty config dir
  file:
    path: "{{ ansible_facts['user_dir'] }}/.config/alacritty"
    state: directory
    mode: '0755'

- name: Download Theme
  git:
    repo: https://github.com/catppuccin/alacritty.git
    dest: "{{ ansible_facts['user_dir'] }}/.config/alacritty/catppuccin"
    depth: 1
    force: yes

- name: Alacritty Copy Config
  copy:
    src: alacritty.toml
    dest: "{{ ansible_facts['user_dir'] }}/.config/alacritty/alacritty.toml"
    mode: '0644'
